### ISSUE TITLE
Xcode 10 crashes with ReadWriteSignal

### ISSUE THREAD

**Issue by fennecos** [iZettle/Flow#34]
# Expected Behavior 
 
The `ReadWriteSignal` setter should not crash
 
# Current Behavior 
 
`ReadWriteSignal` crashes when trying to access its setter
 
# Steps to Reproduce 
 
Here is a simple unit test to reproduce the crash
```swift
    func testReadWriteSignalCrashing() {
        ReadWriteSignal(CGPoint.zero).value.x = 2 // This one crashes for some reason
    }
```

Note that these tests are passing:
```swift
    func testReadWriteSignalNotCrashing() {
        ReadWriteSignal(CGPoint.zero).value = CGPoint(x: 2, y: 0) // This is fine
        let signal = ReadWriteSignal(CGPoint.zero)
        signal.value.x = 2 // This is also fine
    }
```
 
## Context  
 
The test fails when building with Xcode 10
 
## Failure Logs 
 Error:
`Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

**Comment by fennecos** [comment]
@mansbernhardt We are experiencing strange crashes with Flow and Xcode 10.
Really hard to understand what's going on. Maybe you have some ideas about it?

**Comment by mansbernhardt** [comment]
@fennecos I have tried different work-arounds such as storing the setter in the CoreSignal instead of using an associated object. But it will still crash. This must be a regression in the compiler. I would see if we could reduce this to a smaller sample and file a radar.

**Comment by mattiasjahnke** [comment]
Adding a `deinit` to `CoreSignal` shows that the signal instance seems to be deallocated before we hit  the `set` on `value` in `ReadWriteSignal`

**Comment by fennecos** [comment]
Yes, I suspected the associated object. But it’s not that.
I was also ordering about the setter being an optional parameter in the init, and therefore cannot explicitly be marked as escaping, but this does not seems to be the case either.

**Comment by mansbernhardt** [comment]
@mattiasjahnke This is a really interesting finding. This really seems to indicate that the compiler (and ARC) has some serious bug in it?

**Comment by mansbernhardt** [comment]
So by adding a retain hack in CoreSignal's init (`let _ = Unmanaged.passRetained(self)`), we make the test pass. But of course we will leak and several other tests will fail.

Really strange that the instance is deallocated to early. Not sure how we can work around this? I would suggest filing a bug with Apple and point to our GitHub repo and provide the unit test above?

**Comment by mansbernhardt** [comment]
I tested to compile with the snapshots for 4.2 and 5.0 at https://swift.org/download/#snapshots. Both compiler versions crashes (Abort trap: 6) for the line:

```swift
ReadWriteSignal(CGPoint.zero).value.x = 2
```

So this line does not even compile on those versions.

**Comment by mansbernhardt** [comment]
Is the above use-case something that comes up in your code base?

**Comment by fennecos** [comment]
yes it's used in several places. We have some computed properties returning a ReadWriteSignal and we sometimes use it just to set the value.

**Comment by fennecos** [comment]
I played a bit with this bug, and this is the minimum of code I could find that reproduces the issue:
```swift
protocol SomeProtocol { }
class SomeClass: SomeProtocol { }

extension SomeProtocol {
    var someGetter: CGPoint {
        nonmutating set { _ = self }
        get { return .zero }
    }
}

func testReadWriteSignalCrashing2() {
    SomeClass().someGetter.x = 2
}
```
I suspect that it has something to do with the `nonmutating` key-word. I guess the compiler is a bit too agressive since I guess it assumes that the object is safe to be deallocated because it won't be mutated.

**Comment by jckarter** [comment]
@fennecos If your example crashes, then it's definitely a bug. It's true that when the setter is `nonmutating`, then there is nothing formally keeping `SomeClass()` alive after `someGetter` has been accessed, but that's because nothing should even be referring back to the object instance. Deallocating it early should not cause the program to crash. However, I tried copying your program to a single swift file, compiling it, and was unable to reproduce the crash:

```
$ cat ~/foo.swift
import CoreGraphics

protocol SomeProtocol { }
class SomeClass: SomeProtocol { }

extension SomeProtocol {
    var someGetter: CGPoint {
        nonmutating set { _ = self }
        get { return .zero }
    }
}

func testCrashingSetter() {
    SomeClass().someGetter.x = 2
}

$ xcrun swiftc -wmo -O ~/foo.swift
$ ./foo
```

**Comment by jckarter** [comment]
Sorry, that was a paste-o. In my real test, I had `SomeClass().someGetter.x = 2` at top level. Thanks for the complete reproducer!

**Comment by jckarter** [comment]
I filed https://bugs.swift.org/browse/SR-8990. If you find out any more information, we'd appreciate it if you could add it to the bug report too. Thanks again.

**Comment by jckarter** [comment]
@mansbernhardt Were you able to reproduce the assertion failure you saw in https://github.com/iZettle/Flow/issues/34#issuecomment-424802558 with that project too? I tried the latest snapshots for both 4.2 and trunk and did not see a compiler assertion failure, though the runtime crash occurs in all of them.

**Comment by jckarter** [comment]
Thanks!

**Comment by jckarter** [comment]
I think I have a fix: https://github.com/apple/swift/pull/19902 I asked our CI system to build a toolchain, which you'll hopefully be able to try to see if it addresses the problem for you.
