### ISSUE TITLE
Add a signal method for holding a bag?

### ISSUE THREAD

**Issue by nataliq** [iZettle/Flow#82]
I'm wondering whether it is a good idea to add a helper to a signal for holding a dispose bag. I wanted to write down the case to clarify it for myself as well as I'm not sure whether it's a good practice. 

I noticed at few places in our codebase we used `signal.atValue { _ in _ = bag }`. Initially I didn't know what that is, later learnt it will hold the bag until the signal is alive but it still doesn't read in a very straightforward way for me. So question is, is this a bad practice or should we have a helper for it.

Here is the (simplified) case:
```swift
struct MyModel {
    let text: String?

    func materialize() -> (UIView, Signal<String>) {
        let textField = UITextField()
        textField.text = text

        let disposable = textField.copySignal.onValue {
            // do something
        }

        // someone needs to hold the disposable

        let view = UIStackView(arrangedSubviews: [textField]) 
        // in the real world more logic goes here but the user of the API usually cares only about the text events
        return (view, textField.providedSignal.plain().atValue { _ in _ = disposable })
    }
}
```

which we can change to:

```swift
return (view, textField.providedSignal.plain().holding(disposable))
```

and add some tests that make sure that the bag gets disposed.

**Comment by mansbernhardt** [comment]
Potentially zero to many might start listening on a signal, hence you should probably not set up any "sub-listeners" until you have a listener on the returned signal. Hence I think I would write the above as: 

```swift
    func materialize() -> (UIView, Signal<String>) {
        let textField = UITextField()
        textField.text = text

        let view = UIStackView(arrangedSubviews: [textField]) 
        return (view, Signal { callback in
            let bag = DisposeBag() 

            bag += textField.onValue(callback)

            bag += textField.copySignal.onValue { ... }

            return bag
        })
    }
```

The problem by using the above suggested:

```swift
signal.atValue { _ in _ = disposable })
```

would probably mean that the disposable is hold on to until the signal itself is released, no matter if someone ever is listening on the returned signal or if the user have stopped listening a long time ago (but someone, somewhere still keeps hold on a reference to the signal itself)...

Compare this to the Presentation FW use of models where signals are set up to declare what should be done once someone start listening, but won't do anything until that point (if ever, if the model is never materialized). Hence it's safe and also common to have instances of models containing signals, that no-one will every listen to (e.g. a view that is uncommon to visit for a typical user) and that potentially lives for-ever. The signal itself only declares what will happen in the case someone listens to it, but wont take any action until that happens.

**Comment by nataliq** [comment]
That makes sense. I now realize that I gave a misleading initial example and the helper suggested by this issue is gonna be very confusing so I'm gonna close the issue. But since we're already in this conversation I'm gonna post modified example closer to my case anyway (which should have probably been in Form's repository):
```swift
class MySpecialField: UITextField {
    init(text: String?, bag: DisposeBag) {
        super.init(frame: .zero)
        self.text = text

        bag += self.copySignal.onValue {
            // do something while someone is holding the bag
        }
        // there can be more useful subscriptions here
    }
}

struct MyModel {
    let text: String?

    func materialize() -> (UIView, (Signal<String>, Disposable)) { <-- is there a good way to avoid this?
        let bag = DisposeBag()
        let textField = MySpecialField(text: text, bag: bag) // someone needs to hold the bag

        let view = UIStackView(arrangedSubviews: [textField])
        // in the real world more logic goes here but the user of the API usually cares only about the text events
        return (view, (textField.providedSignal.plain(), bag))
    }
}
```

Here it's not possible to apply the above technique because the returned view needs a bag in its initializer. Which basically means "I have some special behaviour that you should keep until you show me". One way to handle this case is to also return the bag. The other way is to have the bag retained by the signal. Do you have any opinions about this? @mansbernhardt @SkyeWelch

**Comment by mansbernhardt** [comment]
@nataliq as for you second example, why do we pass a bag to `MySpecialField` init instead of letting the field itself hold the bag similar to `ValueField`?

**Comment by nataliq** [comment]
This will be a valid use of a `bag` property (and one where [your weak helper](https://github.com/iZettle/Flow/pull/81) can be useful) since the lifecycle of the view is the same as the lifecycle of the subscriptions, right?

If the init is in an extension, on the other hand, passing the bag like this can be an option, too.

**Comment by mansbernhardt** [comment]
I think the problem with trying to move the life time of an external bag into a signal's lifetime will be fragile as the signal (as mentioned before) could be used from 0 to n times, hence how do we decide when the bag should be disposed? This is in contrast to e.g. a future that is guaranteed to run once (with potentially the exception of repeating futures)... That is why I believe a design where we pass a bag to an initializer such as suggested above might bite you back. So if the init lives in an extension with no access to a member bag, perhaps adding one using an associated object might be an option?

```swift
extension MySpecialField {
    init(...) {
       self.init(...)
       let bag = associatedValue(forKey: &bagKey, initial: DisposeBag())

       bag += someSignal.with(weak: self).onValue { `self`, value in 
          ....
       }
}
```

**Comment by nataliq** [comment]
Agreed about not moving bags into signal's lifetime. 

Would you say that the cases in the `Form` framework where we pass bags to initializers (like for example for [tables](https://github.com/iZettle/Form/blob/master/Form/TableKit.swift#L107) and [collections](https://github.com/iZettle/Form/blob/master/Form/CollectionKit.swift#L42)) are following the same pattern and should be potentially changed to use stored bags?

**Comment by mansbernhardt** [comment]
Probably. I don't remember the exact reasoning why we went down the current path of passing the bag  to the initialiser, but I would guess it was related to the handling of retain cycles. It would be interesting to investigate if we could update the kit's to not pass a bag and deprecate the old ones. Based on #81 we could perhaps handle those retain cycles in a nicer way...

**Comment by nataliq** [comment]
Will try it with the new version of Flow. Thanks for the good discussion. I would like to include some more examples to `Form` to illustrate different recommended practices and discussions like this really help.

**Comment by mansbernhardt** [comment]
@nataliq Yes, I agree that these discussions are fruitful. I might have a look at the kits as well..

**Comment by nataliq** [comment]
@mansbernhardt I started using the suggestion you had here: https://github.com/iZettle/Flow/issues/82#issuecomment-487061498

I find it redundant (and maybe even error prone) that we need to call the callback from the new signal on events of the original signal and for read signals we also need to pass the initial value explicitly. I think it will be nice to have a helper but I still have a lot to learn about the internals of CoreSignal.. I tried a solution here but it is not good since it executes the passed block every time a subscription is added: https://github.com/iZettle/Flow/commit/61407982b6af462c22f964a9b0a76ae9b8be8024 . The proper solution, I'm not sure how to turn into a generic one. Here are the concrete versions based on your suggestion: https://github.com/iZettle/Flow/commit/d6354cb15ce9b2e0ba001a5e31a8140f69a9ce98 . I would really appreciate a hint for making it generic.

**Comment by mansbernhardt** [comment]
https://github.com/iZettle/Flow/commit/61407982b6af462c22f964a9b0a76ae9b8be8024 looks good to me. Why would you not expect the closure to be called for every new subscription?

If you only want it to be called for the first subscriber of many simultaneously subscribers you could always add a `shared()` transform to it.
